apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadmbyc2180-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadmbyc2180-tenant-component
    app.kubernetes.io/part-of: loadmbyc2180-tenant-app
  name: loadmbyc2180-tenant-component
  namespace: loadmbyc2180-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: loadmbyc2180-tenant-component
    weight: null
status: {}
